// <auto-generated />
using System;
using CafeManagement.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafeManagement.DAL.Migrations
{
    [DbContext(typeof(CafeContext))]
    [Migration("20260109143442_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CafeManagement.Entity.Entities.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppUserId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppUserId");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            AppUserId = 1,
                            CreatedDate = new DateTime(2026, 1, 9, 21, 34, 42, 275, DateTimeKind.Local).AddTicks(2792),
                            FullName = "Nguyễn Từ Lân",
                            IsActive = true,
                            PasswordHash = "1",
                            Role = "Admin",
                            UserName = "admin"
                        },
                        new
                        {
                            AppUserId = 2,
                            CreatedDate = new DateTime(2026, 1, 9, 21, 34, 42, 275, DateTimeKind.Local).AddTicks(2804),
                            FullName = "Nhân viên",
                            IsActive = true,
                            PasswordHash = "1",
                            Role = "Staff",
                            UserName = "staff"
                        });
                });

            modelBuilder.Entity("CafeManagement.Entity.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Cà phê Việt Nam",
                            Description = "Đậm đà bản sắc",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Trà Trái Cây Trend",
                            Description = "Mát lạnh",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Trà Sữa & Kem",
                            Description = "Béo ngậy",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Đá Xay & Smoothie",
                            Description = "Sảng khoái",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("CafeManagement.Entity.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("TableId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CafeManagement.Entity.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("CafeManagement.Entity.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            IsAvailable = true,
                            Price = 29000m,
                            ProductName = "Cà phê Muối Huế"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            IsAvailable = true,
                            Price = 35000m,
                            ProductName = "Cà phê Trứng Hà Nội"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            IsAvailable = true,
                            Price = 32000m,
                            ProductName = "Bạc Xỉu Cốt Dừa"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            IsAvailable = true,
                            Price = 45000m,
                            ProductName = "Cold Brew Cam Vàng"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1,
                            IsAvailable = true,
                            Price = 39000m,
                            ProductName = "Cà phê Sữa Hạt Dẻ"
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 1,
                            IsAvailable = true,
                            Price = 42000m,
                            ProductName = "Latte Khoai Môn"
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1,
                            IsAvailable = true,
                            Price = 39000m,
                            ProductName = "Cà Phê Dừa Đá Xay"
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 1,
                            IsAvailable = true,
                            Price = 35000m,
                            ProductName = "Espresso Tonic"
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 2,
                            IsAvailable = true,
                            Price = 35000m,
                            ProductName = "Trà Mãng Cầu Xiêm"
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 2,
                            IsAvailable = true,
                            Price = 45000m,
                            ProductName = "Trà Măng Cụt Hoa Đậu Biếc"
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 2,
                            IsAvailable = true,
                            Price = 35000m,
                            ProductName = "Trà Ổi Hồng Muối Ớt"
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 2,
                            IsAvailable = true,
                            Price = 39000m,
                            ProductName = "Trà Dâu Tằm Pha Lê"
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 2,
                            IsAvailable = true,
                            Price = 42000m,
                            ProductName = "Trà Nhãn Sen Vàng"
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 2,
                            IsAvailable = true,
                            Price = 39000m,
                            ProductName = "Trà Lựu Đỏ Hạt Chia"
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 2,
                            IsAvailable = true,
                            Price = 39000m,
                            ProductName = "Trà Vải Hoa Hồng"
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 2,
                            IsAvailable = true,
                            Price = 35000m,
                            ProductName = "Trà Đào Cam Sả"
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 2,
                            IsAvailable = true,
                            Price = 38000m,
                            ProductName = "Lục Trà Kiwi Táo Xanh"
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 2,
                            IsAvailable = true,
                            Price = 38000m,
                            ProductName = "Trà Hibiscus Dâu Tây"
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 3,
                            IsAvailable = true,
                            Price = 45000m,
                            ProductName = "Trà Sữa Nướng Vân Nam"
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 3,
                            IsAvailable = true,
                            Price = 40000m,
                            ProductName = "Sữa Tươi Trân Châu Đường Đen"
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 3,
                            IsAvailable = true,
                            Price = 42000m,
                            ProductName = "Trà Sữa Oolong Lài Kem Cheese"
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 3,
                            IsAvailable = true,
                            Price = 45000m,
                            ProductName = "Trà Sữa Than Tre Nhật Bản"
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 3,
                            IsAvailable = true,
                            Price = 45000m,
                            ProductName = "Matcha Latte Kem Trứng"
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 3,
                            IsAvailable = true,
                            Price = 30000m,
                            ProductName = "Trà Sữa Thái Xanh"
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 3,
                            IsAvailable = true,
                            Price = 35000m,
                            ProductName = "Hồng Trà Macchiato"
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryId = 3,
                            IsAvailable = true,
                            Price = 45000m,
                            ProductName = "Sữa Tươi Kem Trứng Nướng"
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryId = 4,
                            IsAvailable = true,
                            Price = 49000m,
                            ProductName = "Cookie Đá Xay Bạc Hà"
                        },
                        new
                        {
                            ProductId = 28,
                            CategoryId = 4,
                            IsAvailable = true,
                            Price = 55000m,
                            ProductName = "Sinh Tố Bơ Dừa Sáp"
                        },
                        new
                        {
                            ProductId = 29,
                            CategoryId = 4,
                            IsAvailable = true,
                            Price = 45000m,
                            ProductName = "Sữa Chua Hy Lạp Granola"
                        },
                        new
                        {
                            ProductId = 30,
                            CategoryId = 4,
                            IsAvailable = true,
                            Price = 35000m,
                            ProductName = "Chanh Tuyết Cốt Dừa"
                        });
                });

            modelBuilder.Entity("CafeManagement.Entity.Entities.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ShiftId");

                    b.HasIndex("UserId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("CafeManagement.Entity.Entities.Table", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TableId");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            TableId = 1,
                            Capacity = 4,
                            Status = "Available",
                            TableName = "Bàn 1"
                        },
                        new
                        {
                            TableId = 2,
                            Capacity = 4,
                            Status = "Available",
                            TableName = "Bàn 2"
                        },
                        new
                        {
                            TableId = 3,
                            Capacity = 4,
                            Status = "Available",
                            TableName = "Bàn 3"
                        },
                        new
                        {
                            TableId = 4,
                            Capacity = 6,
                            Status = "Available",
                            TableName = "Bàn 4"
                        },
                        new
                        {
                            TableId = 5,
                            Capacity = 8,
                            Status = "Available",
                            TableName = "Bàn 5"
                        },
                        new
                        {
                            TableId = 6,
                            Capacity = 2,
                            Status = "Available",
                            TableName = "Bàn 6"
                        },
                        new
                        {
                            TableId = 7,
                            Capacity = 2,
                            Status = "Available",
                            TableName = "Bàn 7"
                        },
                        new
                        {
                            TableId = 8,
                            Capacity = 10,
                            Status = "Available",
                            TableName = "Bàn 8"
                        });
                });

            modelBuilder.Entity("CafeManagement.Entity.Entities.Order", b =>
                {
                    b.HasOne("CafeManagement.Entity.Entities.Table", "Table")
                        .WithMany("Orders")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeManagement.Entity.Entities.AppUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CafeManagement.Entity.Entities.OrderDetail", b =>
                {
                    b.HasOne("CafeManagement.Entity.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeManagement.Entity.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CafeManagement.Entity.Entities.Product", b =>
                {
                    b.HasOne("CafeManagement.Entity.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CafeManagement.Entity.Entities.Shift", b =>
                {
                    b.HasOne("CafeManagement.Entity.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CafeManagement.Entity.Entities.AppUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CafeManagement.Entity.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CafeManagement.Entity.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("CafeManagement.Entity.Entities.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("CafeManagement.Entity.Entities.Table", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
